export { default as Banner } from './Banner'
export { default as Footer } from './Footer'
export { default as Carousel } from './Carousel'
export { default as HeaderNav} from './HeaderNav'
export { default as Sidemeun } from './Sidemeun'
export { default as SectionAbout } from './SectionAbout'
export { default as SectionService } from './SectionService'
export { default as SectionTitle } from './SectionTitle'
export {default as Partner} from './Partner'
export {default as SwiperService} from './SwiperService'
export {default as WhyChooseUs} from './WhyChooseUs'
export { default as AboutHeroSection } from './AboutHeroSection'
